In [0]:
import numpy as np

eps = [0, 10**-15, 10**-14, 10**-10]
for i in eps:
  A = [[1, i], [0, 1+i]]
  eigval, eigvect = np.linalg.eig(A)
  print ('Eps: {}'.format(i))
  print ('Eigenvals: {}'.format(eigval))
  print ('Eigenvectors:\n{}'.format(eigvect))
  print ('Angle (v1, v2): {:.6} degrees\n'.format(np.arccos(np.dot(eigvect[:,0], eigvect[:,1])) * 180 / np.pi))
  
print ('So, we see that the eigenvectors for eps != 0 are not almost orthogonal.')

Eps: 0
Eigenvals: [1. 1.]
Eigenvectors:
[[1. 0.]
 [0. 1.]]
Angle (v1, v2): 90.0 degrees

Eps: 1e-15
Eigenvals: [1. 1.]
Eigenvectors:
[[1.         0.66926022]
 [0.         0.7430281 ]]
Angle (v1, v2): 47.99 degrees

Eps: 1e-14
Eigenvals: [1. 1.]
Eigenvectors:
[[1.         0.70738943]
 [0.         0.70682402]]
Angle (v1, v2): 44.9771 degrees

Eps: 1e-10
Eigenvals: [1. 1.]
Eigenvectors:
[[1.         0.70710675]
 [0.         0.70710681]]
Angle (v1, v2): 45.0 degrees

So, we see that the eigenvectors for eps != 0 are not almost orthogonal.
